export enum USER_AUTHORITITY {
	ADMIN = 'ROLE_ADMIN',
	USER = 'ROLE_USER',
	GUEST = 'ROLE_GUEST',
	'API_CODE:QUERY' = 'API_CODE:QUERY',
	'API_CODE:CREATE' = 'API_CODE:CREATE',
	'API_CODE:UPDATE' = 'API_CODE:UPDATE',
	'API_CODE:DELETE' = 'API_CODE:DELETE',
	'API_CODE:PUBLISH' = 'API_CODE:PUBLISH',
	'USER_MANAGEMENT.ROLE:CREATE' = 'USER_MANAGEMENT.ROLE:CREATE',
	'USER_MANAGEMENT.ROLE:DELETE' = 'USER_MANAGEMENT.ROLE:DELETE',
	'USER_MANAGEMENT.ROLE:UPDATE' = 'USER_MANAGEMENT.ROLE:UPDATE',
	'USER_MANAGEMENT.ROLE:QUERY' = 'USER_MANAGEMENT.ROLE:QUERY',
	'USER_MANAGEMENT:QUERY' = 'USER_MANAGEMENT:QUERY',
	'USER_MANAGEMENT.PERMISSION:CREATE' = 'USER_MANAGEMENT.PERMISSION:CREATE',
	'USER_MANAGEMENT.PERMISSION:DELETE' = 'USER_MANAGEMENT.PERMISSION:DELETE',
	'USER_MANAGEMENT.PERMISSION:UPDATE' = 'USER_MANAGEMENT.PERMISSION:UPDATE',
	'USER_MANAGEMENT.PERMISSION:QUERY' = 'USER_MANAGEMENT.PERMISSION:QUERY',
	'USER_MANAGEMENT.ROLE_PERMISSION:CREATE' = 'USER_MANAGEMENT.ROLE_PERMISSION:CREATE',
	'USER_MANAGEMENT.ROLE_PERMISSION:DELETE' = 'USER_MANAGEMENT.ROLE_PERMISSION:DELETE',
	'USER_MANAGEMENT.ROLE_PERMISSION:UPDATE' = 'USER_MANAGEMENT.ROLE_PERMISSION:UPDATE',
	'USER_MANAGEMENT.ROLE_PERMISSION:QUERY' = 'USER_MANAGEMENT.ROLE_PERMISSION:QUERY',
	'USER_MANAGEMENT.USER_ROLE:CREATE' = 'USER_MANAGEMENT.USER_ROLE:CREATE',
	'USER_MANAGEMENT.USER_ROLE:DELETE' = 'USER_MANAGEMENT.USER_ROLE:DELETE',
	'USER_MANAGEMENT.USER_ROLE:UPDATE' = 'USER_MANAGEMENT.USER_ROLE:UPDATE',
	'USER_MANAGEMENT.USER_ROLE:QUERY' = 'USER_MANAGEMENT.USER_ROLE:QUERY'
}

export enum ROLE_TYPE {
	SYSTEM = 'SYSTEM',
	CUSTOM = 'CUSTOM'
}
