export enum USER_MANAGEMENT_TYPE {
	USER_ROLE = 'USER_ROLE',
	ROLE_PERMISSION = 'ROLE_PERMISSION',
	PERMISSION = 'PERMISSION',
	ROLE = 'ROLE'
}

export enum PERMISSION_TYPE {
	API = 'API',
	CUSTOM = 'CUSTOM'
}
